---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать игру
  - При создании игры, пользователь должен иметь возможность выбрать с кем он хочет играть (друг, компьютер, другой пользователь)
  - При создании игры, пользователь должен иметь возможность выбрать уровень сложности (4 уровня)
  - При создании игры, пользователь должен иметь возможность выбрать время на выполнение задания
  - При создании игры, пользователь должен иметь возможность выбрать задание
  - Пользователь должен иметь возможность присоединиться к игре
  - Пользователь должен иметь возможность выбрать язык программирования, на котором он будет учавствовать в играх
  - Во время игры, пользователь должен иметь возможность сдаться во время игры
  - Во время игры, должен быть создан чат, для общения между игроками
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность автороизоваться через GitHub
  - Пользователь должен иметь возможность отменить созданную им игру до того, как она началась
  - В игре должна быть реализована статистика побед/поражений
  - Пользователи должны иметь возможность просматривать статистику всех игроков
  - Пользователи должны иметь возможность видеть других пользователей, которые сейчас находятся на сайте
  - В игре должна быть реализована таблица лидеров по статистике (за месяц, неделю или все время)
